[DEFAULT]
OPERATOR = "Javier Morales"
PLACE = "Ciemat"
CONFIG FILE = "/C/Trabajo_Robot/Test Asic Javi_2021/Origen Socket SERVO_PCB_BUENO_v5 (muchos asics)/CONFIG/configuracion_robot_CTAV2022A.test"
PATH OUT = "/C/Trabajo_Robot/QC_LSTSUR"