[DEFAULT]
ASIC = "ATL1v2E64409.1118-130000"
OPERATOR = "Gustavo Martínez"
PLACE = "Ciemat"
PATH OUT = "/C/Trabajo_Robot/Pruebas_Bruno"
CONFIG FILE = "/C/Trabajo_Robot/Test Asic Javi_2021/Origen Socket SERVO_PCB_BUENO_v5 (muchos asics)/CONFIG/configuracion_robot_CTAV2022A.test"